[package]
name = "charmer-lsf"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
charmer-parsers.workspace = true
chrono.workspace = true
thiserror.workspace = true
tokio.workspace = true
