[package]
name = "charmer-slurm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
charmer-parsers.workspace = true
tokio.workspace = true
regex.workspace = true
thiserror.workspace = true
chrono.workspace = true
tracing.workspace = true
